Add variable exercise

diff --git a/.github/workflows/hello-variables.yml b/.github/workflows/hello-variables.yml
--- a/.github/workflows/hello-variables.yml
+++ b/.github/workflows/hello-variables.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: Hello world
+name: Hello variables
 
 # Controls when the workflow will run
 on:
@@ -12,6 +12,10 @@ on:
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+
+# Set global environment variable
+env:
+  ENVIRONMENT: acc
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -25,12 +29,23 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      # Runs a single command using the runner's shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      # Runs a set of commands using the runner's shell
+      - name: check environment
+        run: |
+          if [ "$ENVIRONMENT" = "acc" ]; then
+            echo "Pass!"
+          else
+            echo "Invalid environment: $ENVIRONMENT"
+            exit 1
+          fi
 
       # Runs a set of commands using the runner's shell
-      - name: Run a multi-line script
+      - name: check environment
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if [ "$ENVIRONMENT" = "prd" ]; then
+            echo "Pass!"
+          else
+            echo "Invalid environment: $ENVIRONMENT"
+            exit 1
+          fi
+        #FIXME add something on this line to make ENVIRONMENT be equal to prd, you may only modify this line
